// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcMOyOQVV7hLM9PFd4gi1DcG94IN7l8iw',
    appId: '1:1048728172664:web:09aa8d36aed98191bed58d',
    messagingSenderId: '1048728172664',
    projectId: 'mobile-470d7',
    authDomain: 'mobile-470d7.firebaseapp.com',
    databaseURL: 'https://mobile-470d7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-470d7.appspot.com',
    measurementId: 'G-VKZ7H18RWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmke_U_eHUmo04N80IK8PMvjYMKIi2CAA',
    appId: '1:1048728172664:android:9f0e425acb99e313bed58d',
    messagingSenderId: '1048728172664',
    projectId: 'mobile-470d7',
    databaseURL: 'https://mobile-470d7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-470d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaUKLo2njqBBQ0mV_qfb276UnKIo7vBHE',
    appId: '1:1048728172664:ios:0524d0165988fe05bed58d',
    messagingSenderId: '1048728172664',
    projectId: 'mobile-470d7',
    databaseURL: 'https://mobile-470d7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-470d7.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaUKLo2njqBBQ0mV_qfb276UnKIo7vBHE',
    appId: '1:1048728172664:ios:0524d0165988fe05bed58d',
    messagingSenderId: '1048728172664',
    projectId: 'mobile-470d7',
    databaseURL: 'https://mobile-470d7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-470d7.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcMOyOQVV7hLM9PFd4gi1DcG94IN7l8iw',
    appId: '1:1048728172664:web:b5484680b96ec5fcbed58d',
    messagingSenderId: '1048728172664',
    projectId: 'mobile-470d7',
    authDomain: 'mobile-470d7.firebaseapp.com',
    databaseURL: 'https://mobile-470d7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-470d7.appspot.com',
    measurementId: 'G-V4Y5G2DQ2G',
  );
}
